### ISSUE TITLE
health_check.py breaks importing on fresh install of Ubuntu 22.04

### ISSUE THREAD

**Issue by teaishealthy** [nextcord/nextcord#1011]
### Summary

health_check.py fails on fresh install of Ubuntu 22.04 because of pre-installed package

### Reproduction Steps

1. Install Ubuntu 22.04.2 (jammy) / or `apt install distro-info`
2. import nextcord
3. Observe

Explanation:
distro-info is preinstalled on Ubuntu 22.04.2 (can be checked with `wget https://releases.ubuntu.com/jammy/ubuntu-22.04.2-desktop-amd64.manifest -q -O - | cut -f 1  | grep distro-info`), it features a weird version number `1.1build1` that pkg_resources fails to parse, which causes an exception that is not handled by nextcord.

### Minimal Reproducible Code

```python
import nextcord
```

### Expected Results

nextcord gets imported

### Actual Results

```py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/teaishealthy/.local/lib/python3.10/site-packages/nextcord/__init__.py", line 42, in <module>
    from .health_check import *
  File "/home/teaishealthy/.local/lib/python3.10/site-packages/nextcord/health_check.py", line 18, in <module>
    get_distribution(library)
  File "/home/teaishealthy/.local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 514, in get_distribution
    dist = get_provider(dist)
  File "/home/teaishealthy/.local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 386, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/home/teaishealthy/.local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 956, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/teaishealthy/.local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 815, in resolve
    dist = self._resolve_dist(
  File "/home/teaishealthy/.local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 844, in _resolve_dist
    env = Environment(self.entries)
  File "/home/teaishealthy/.local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1044, in __init__
    self.scan(search_path)
  File "/home/teaishealthy/.local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1077, in scan
    self.add(dist)
  File "/home/teaishealthy/.local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1096, in add
    dists.sort(key=operator.attrgetter('hashcmp'), reverse=True)
  File "/home/teaishealthy/.local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2640, in hashcmp
    self.parsed_version,
  File "/home/teaishealthy/.local/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2694, in parsed_version
    raise packaging.version.InvalidVersion(f"{str(ex)} {info}") from None
pkg_resources.extern.packaging.version.InvalidVersion: Invalid version: '1.1build1' (package: distro-info)
```

### Intents

N/A

### System Information

That also epicly failed:

nextcord==2.4.1
Ubuntu 22.04.2 jammy
Python 3.10

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by fisherrjd** [comment]
I am having a similar issue but it cannot find the module 'pkg_resources" seen on python 3.10 and 3.11

**Comment by teaishealthy** [comment]
Not nextcords fault and I should've been using a non-system/managed python enviroment or a venv.
