### ISSUE TITLE
Regression in StringSelect types

### ISSUE THREAD

**Issue by Skelmis** [nextcord/nextcord#1103]
### Summary

Master branch has a StringSelect regression where subclassing now break with the error seen below

### Reproduction Steps

Use the following code with the master branch. https://paste.disnake.dev/?id=1690608278173887

### Expected Results

Select works as expected

### Actual Results

```
Ignoring exception in on_ready
Traceback (most recent call last):
  File "/home/skelmis/Code/test_ creds/venv/lib/python3.10/site-packages/nextcord/client.py", line 497, in _run_event
    await coro(*args, **kwargs)
  File "/home/skelmis/Code/test_ creds/main.py", line 43, in on_ready
    bot.add_view(MyView(bot))
  File "/home/skelmis/Code/test_ creds/main.py", line 13, in __init__
    self.add_item(MySelect())
  File "/home/skelmis/Code/test_ creds/main.py", line 31, in __init__
    super().__init__(
  File "/home/skelmis/Code/test_ creds/venv/lib/python3.10/site-packages/nextcord/ui/select/string.py", line 86, in __init__
    super().__init__(
  File "/home/skelmis/Code/test_ creds/venv/lib/python3.10/site-packages/nextcord/ui/select/base.py", line 123, in __init__
    self._underlying = SelectMenu._raw_construct(
  File "/home/skelmis/Code/test_ creds/venv/lib/python3.10/site-packages/nextcord/components.py", line 85, in _raw_construct
    setattr(self, slot, value)
AttributeError: 'StringSelectMenu' object attribute 'type' is read-only

```

### Intents

N/A

### System Information

Master branch

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

Initially reported [here](1133141064639860837)

**Comment by Skelmis** [comment]
Debugging info:
On pypi, when hitting `_raw_construct` no values are set on the instance. On master, `self.type` is already set and is a read property which means it fails to be modified

**Comment by Skelmis** [comment]
The reason for this change appears to [this](https://github.com/nextcord/nextcord/blob/master/nextcord/components.py#L284) line which is the difference between versions and comes from the pyright PR

Theres 2 ways of fixing this, either correcting `_raw_construct` so that it handles preset types or simply reverting this change. I'm opting for the initial fix, albiet a tad hacky

**Comment by Skelmis** [comment]
Upon further investigation, this relates to all menus which now have type preset as a literal
