### ISSUE TITLE
Cannot edit an InteractionMessage

### ISSUE THREAD

**Issue by apsw171118** [nextcord/nextcord#1168]
### Summary

Cannot edit a message using the function .edit

### Reproduction Steps

"Dropping existing records..\nApplying new records..." basically returns this:
Ignoring exception in command <nextcord.application_command.SlashApplicationSubcommand object at 0x0000022FF5DE32F0>:
Traceback (most recent call last):
  File "C:\Users\ng_jo\AppData\Local\Programs\Python\Python312\Lib\site-packages\nextcord\application_command.py", line 918, in invoke_callback_with_hooks
    await self(interaction, *args, **kwargs)
  File "C:\Users\ng_jo\OneDrive\Backup\Desktop\joshuang\coding\.GITHUBCLONE\Testing-Bot\cogs\tickets\__init__.py", line 319, in register_config
    await msg.edit(
  File "C:\Users\ng_jo\AppData\Local\Programs\Python\Python312\Lib\site-packages\nextcord\interactions.py", line 1180, in edit
    message = await self._state._interaction.edit_original_message(
                    ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConnectionState' object has no attribute '_interaction'

The above exception was the direct cause of the following exception:

nextcord.errors.ApplicationInvokeError: Command raised an exception: AttributeError: 'ConnectionState' object has no attribute '_interaction'

 

### Minimal Reproducible Code

```python
@setup.subcommand(name="register")
    # @application_checks.is_owner()
    async def register_config(
        self,
        interaction,
        guild_id=str,
        category_id=str,
        staff_id=str,
        transcript_id=str,
    ):
        guild = self.bot.get_guild(int(guild_id))
        if self.bot.get_guild(int(guild_id)):
            if guild.get_channel(int(transcript_id)):
                if nextcord.utils.get(guild.categories, id=int(category_id)):
                    if not fetch(
                        "storage/tickets.sqlite",
                        "TicketConfig",
                        f"guild_id={guild_id}",
                    ):
                        insert(
                            "storage/tickets.sqlite",
                            "TicketConfig",
                            ("guild_id", "category_id", "staff_id", "transcript_id"),
                            (guild_id, category_id, staff_id, transcript_id),
                        )
                    else:
                        view = ConfirmView()
                        data = fetch("storage/tickets.sqlite", "TicketConfig")
                        for i in range(len(data)):
                            if data[i][0] == int(guild_id):
                                data = data[i]
                                break
                        msg = await interaction.response.send_message(
                            f"Guild already registered, overwrite?\n### CONFIGURATION FOR THIS GUILD\n- Guild ID: {interaction.guild.name} ({data[0]})\n- Category ID: <#{data[1]}> ({data[1]})\n- Staff ID: <@&{data[2]}> ({data[2]}\n- Transcript Channel: <#{data[3]}> ({data[3]})",
                            view=view,
                        )
                        await view.wait()
                        if view is None:
                            await msg.edit("Action cancelled.")
                        elif view.value:
                            msg = await msg.edit(
                                content="Overwriting the existing record...", view=None
                            )
                            drop(
                                "storage/tickets.sqlite",
                                "TicketConfig",
                                f"guild_id={guild_id}",
                            )
                            await msg.edit(
                                "Dropped existing records..\nApplying new records..."
                            )
                            insert(
                                "storage/tickets.sqlite",
                                "TicketConfig",
                                (
                                    "guild_id",
                                    "category_id",
                                    "staff_id",
                                    "transcript_id",
                                ),
                                (guild_id, category_id, staff_id, transcript_id),
                            )
                            # await msg.edit(
                            #    f"Registered guild.\n{fetch('storage/tickets.sqlite', 'TicketConfig', f'WHERE guild_id={guild_id}')}"
                            # )
                else:
                    await interaction.response.send_message(
                        "Invalid `category_id`. Perhaps the bot doesn't have the permission to view it?"
                    )
            else:
                await interaction.response.send_message(
                    "Invalid `transcript_id`. Maybe the bot doesn't have access to all the channels?"
                )
        else:
            await interaction.response.send_message(
                "Invalid `guild_id`, maybe the bot is not in the guild?"
            )
```

### Expected Results

edit the message

### Actual Results

threw me an error idk what it means

### Intents

nextcord.Intents.all()

### System Information

nextcord-ext-menus 1.5.7
- Python v3.12.1-final
- nextcord v2.6.0-final
- aiohttp v3.9.1
- system info: Windows 10 10.0.19045
i've got discord.py i don't think it would affect it tho...

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

support thread here: https://ptb.discord.com/channels/881118111967883295/1212126972784807987

**Comment by ooliver1** [comment]
Can you make the minimal reproducible code actually minimal? It's hard to understand with multiple nested conditions.

**Comment by apsw171118** [comment]
```Python
@nextcord.slash_command(name="bug-test")
async def bugtest(self, interaction):
    msg = await interaction.response.send_message("abc1")
    msg = await msg.edit("abc2")
    msg = await msg.edit("abc3")```
At third edit:
![image](https://github.com/nextcord/nextcord/assets/77912444/c494398b-ec1b-4ffc-82bb-1151e374840d)
```Python
Ignoring exception in command <nextcord.application_command.SlashApplicationCommand object at 0x00000244D4B5D3D0>:
Traceback (most recent call last):
  File "C:\Users\ng_jo\AppData\Local\Programs\Python\Python312\Lib\site-packages\nextcord\application_command.py", line 918, in invoke_callback_with_hooks
    await self(interaction, *args, **kwargs)
  File "C:\Users\ng_jo\OneDrive\Backup\Desktop\joshuang\coding\.GITHUBCLONE\Testing-Bot\cogs\dev\__init__.py", line 123, in bugtest
    msg = await msg.edit("abc3")
          ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ng_jo\AppData\Local\Programs\Python\Python312\Lib\site-packages\nextcord\interactions.py", line 1180, in edit
    message = await self._state._interaction.edit_original_message(
                    ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConnectionState' object has no attribute '_interaction'

The above exception was the direct cause of the following exception:

nextcord.errors.ApplicationInvokeError: Command raised an exception: AttributeError: 'ConnectionState' object has no attribute '_interaction'```

![image](https://github.com/nextcord/nextcord/assets/77912444/c9c51562-9fd7-4db2-a3ae-5848035b5eea)

**Comment by teaishealthy** [comment]
Can reproduce. 

As a temporary fix you can not collect the message until the end:

```py
@nextcord.slash_command(name="bug-test")
async def bugtest(self, interaction):
    msg = await interaction.response.send_message("abc1")
    await msg.edit("abc2")
    msg = await msg.edit("abc3")
	print(msg.content)  # abc3
```
