### ISSUE TITLE
Bot crashing due to the error "aiohttp.http_websocket.WebSocketError: Received fragmented control frame"

### ISSUE THREAD

**Issue by MarineMasta** [nextcord/nextcord#1170]
### Summary

Every few days,  one of my bots will crash with the "received fragmented control frame" error

### Reproduction Steps

Hard to reproduce, as it seems to be randomly triggered. Does happen every few days on bots that I have running 24/7.

### Expected Results

Error should be ignored or socket should close gracefully.

### Actual Results

Traceback (most recent call last):
  File "/bots/bot/script.py", line 2266, in <module>
    bot.run(TOKEN)
  File "/usr/local/lib/python3.10/dist-packages/nextcord/client.py", line 863, in run
    return future.result()
  File "/usr/local/lib/python3.10/dist-packages/nextcord/client.py", line 842, in runner
    await self.start(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/nextcord/client.py", line 806, in start
    await self.connect(reconnect=reconnect)
  File "/usr/local/lib/python3.10/dist-packages/nextcord/client.py", line 701, in connect
    await self.ws.poll_event()
  File "/usr/local/lib/python3.10/dist-packages/nextcord/gateway.py", line 615, in poll_event
    raise msg.data
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/client_ws.py", line 196, in close
    msg = await self._reader.read()
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py", line 657, in read
    return await super().read()
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py", line 627, in read
    raise self._exception
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/client_ws.py", line 229, in receive
    msg = await self._reader.read()
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py", line 657, in read
    return await super().read()
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/streams.py", line 616, in read
    await self._waiter
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/http_websocket.py", line 288, in feed_data
    return self._feed_data(data)
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/http_websocket.py", line 295, in _feed_data
    for fin, opcode, payload, compressed in self.parse_frame(data):
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/http_websocket.py", line 459, in parse_frame
    raise WebSocketError(
aiohttp.http_websocket.WebSocketError: Received fragmented control frame

### Intents

Default

### System Information

Python v3.10.6-final
nextcord v2.2.0-final
aiohttp v3.8.3
system info: Linux 5.15.0-52-generic

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

This is the same issue discord.py encountered a few months ago: https://github.com/Rapptz/discord.py/discussions/9561#discussion-5625288

The fix for discord.py, which seems like it could be applied to nextcord's gateway.py: https://github.com/Rapptz/discord.py/commit/163a86c4a031f7ecd856f45a74da47e63b17bb16

**Comment by Kevin-OVI** [comment]
My bots also crashed multiple times with this same error. I made a pull request implementing the fix from discord.py (#1180).
