### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by KaityXD** [nextcord/nextcord#1226]
### Summary

This is my skill issues 

### Reproduction Steps

```
Ignoring exception in command None:
nextcord.ext.commands.errors.CommandNotFound: Command "ava" is not found
Ignoring exception in on_interaction
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/nextcord/client.py", line 522, in _run_event
    await coro(*args, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/nextcord/client.py", line 2177, in on_interaction
    await self.process_application_commands(interaction)
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/nextcord/client.py", line 2197, in process_application_commands
    await app_cmd.call_from_interaction(interaction)
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/nextcord/application_command.py", line 2605, in call_from_interaction
    await self.call(self._state, interaction)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/nextcord/application_command.py", line 2973, in call
    await self.call_slash(state, interaction, option_data)
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/nextcord/application_command.py", line 1920, in call_slash
    kwargs = await self.get_slash_kwargs(state, interaction, option_data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/nextcord/application_command.py", line 1884, in get_slash_kwargs
    kwargs[self.options[arg_data["name"]].functional_name] = await self._options[
                                                             ^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/nextcord/application_command.py", line 1745, in handle_value
    user_dict = {user.id: user for user in get_users_from_interaction(state, interaction)}
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/nextcord/application_command.py", line 3524, in get_users_from_interaction
    raise TypeError("Cannot resolve members if Interaction.guild is None")
TypeError: Cannot resolve members if Interaction.guild is None
```

code was from https://github.com/kaityxd/discord_bot/blob/main/cogs/avatar_cog.py

### Minimal Reproducible Code

```python
dawg
```

### Expected Results

fetch user pfp without using guildy friend have done this with discordmpy idk how

### Actual Results

error up there

### Intents

it is .all()

### System Information

- Python v3.12.7-final
- nextcord v3.0.0-alpha
    - nextcord metadata: ppv3.0.0a65+g9f7e4bf
- aiohttp v3.10.10
- system info: Linux 4.19.191+ #1 SMP PREEMPT Wed Sep 4 04:08:57 CST 2024

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

help

**Comment by EmmmaTech** [comment]
for future reference, you may find more helpful and quick guidance on our [official discord server](https://discord.gg/nextcord). the issue tracker is meant to report issues with the library itself.
and as oliver said, make sure to give us more context about your problem. where did you run the command? what snippet of code does the issue arise from?

**Comment by KaityXD** [comment]
i feel guilty using github issues rn but i trying to use dm context but how
do i uhhh use nextcord.Meber in dm or other guilds

**Comment by EmmmaTech** [comment]
firstly, you can't use the member class in a dm context. no members exist there, only user objects. secondly, you can't use the member class in other guilds because apps installed in a user context have no permissions in guilds they are invoked in.

**Comment by KaityXD** [comment]
thx for replying
but i saw my friend do it with discord.py in same method how can i do
something like that in nextcord
