### ISSUE TITLE
ImportError still occurring

### ISSUE THREAD

**Issue by piotr25691** [nextcord/nextcord#141]
### Summary

libraries using d.py still throw an error

### Reproduction Steps

after uninstalling discord.py (being incompatible) the error started

### Expected Results

they should've just imported and then work

### Actual Results

```py
 File "/home/container/.local/lib/python3.8/site-packages/nextcord/ext/commands/bot.py", line 661, in _load_from_module_spec
    spec.loader.exec_module(lib)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/container/process-nr/cogs/slash.py", line 18, in <module>
    import dbl
  File "/home/container/.local/lib/python3.8/site-packages/dbl/__init__.py", line 18, in <module>
    from .client import DBLClient
  File "/home/container/.local/lib/python3.8/site-packages/dbl/client.py", line 35, in <module>
    from discord import Client
ImportError: cannot import name 'Client' from 'discord' (unknown location)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/container/.local/lib/python3.8/site-packages/nextcord/client.py", line 351, in _run_event
    await coro(*args, **kwargs)
  File "/home/container/process-nr/main.py", line 417, in on_ready
    init_config()
  File "/home/container/process-nr/main.py", line 114, in init_config
    client.load_extension(f'cogs.{filename[:-3]}')
  File "/home/container/.local/lib/python3.8/site-packages/nextcord/ext/commands/bot.py", line 733, in load_extension
    self._load_from_module_spec(spec, name)
  File "/home/container/.local/lib/python3.8/site-packages/nextcord/ext/commands/bot.py", line 664, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
nextcord.ext.commands.errors.ExtensionFailed: Extension 'cogs.slash' raised an error: ImportError: cannot import name 'Client' from 'discord' (unknown location)
```

### Intents

Intents.members

### System Information

```py
- Python v3.8.10-final
- nextcord v2.0.0-alpha
    - nextcord pkg_resources: v2.0.0a2
- aiohttp v3.7.3
- system info: Linux 5.4.0-47-generic #51-Ubuntu SMP Fri Sep 4 19:50:52 UTC 2020
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by TAG-Epic** [comment]
Do you have any reproducible code?

**Comment by piotr25691** [comment]
> Do you have any reproducible code?

i have not changed any code since this error occurred

**Comment by TAG-Epic** [comment]
Do you have some code I can run to get the same error as you so I can test on my machine?

**Comment by piotr25691** [comment]
> Do you have some code I can run to get the same error as you so I can test on my machine?

i got it by this code

```py
import dbl
dblpy = dbl.DBLClient(client, token)
``` 
just provide whatever we only need to see the import issue

**Comment by sairam4123** [comment]
Well.. I don't think DBL is supported by nextcord.

**Comment by ooliver1** [comment]
That's not helpful isn't it, we want 3rd party libraries to work with nextcord lol

**Comment by sairam4123** [comment]
Umm.. then I think it's caused by the compatibility layer. I certainly have no clue.

**Comment by rf20008** [comment]
this would mean we need aliases for everything in nextcord or importerrors will occur

**Comment by piotr25691** [comment]
> Well.. I don't think DBL is supported by nextcord.

for the time being i have forked the project and changed the module imports regarding discord.py to make the library work

**Comment by veni-vidi-code** [comment]
Mmmh... the problem is that the requirements of dbl include discord.py so it installs it / depends on it. In order of it to work it should be enough to replace this instead of the imports

**Comment by The-Bow-Hunter** [comment]
Could you please try installing it and uninstalling discord.py afterwards

**Comment by ooliver1** [comment]
The 'alias' 'compat' is never going to work, why can't we just delete it. 

And no you do not have to make a fork for everything, there is others that can do that.

**Comment by ooliver1** [comment]
Back to this apparently it's fixed @piotr25691

**Comment by piotr25691** [comment]
> Back to this apparently it's fixed @piotr25691

what happened exactly?

**Comment by piotr25691** [comment]
this issue can be partially resolved (will throw warnings) if you:
> 1. install the latest version of d.py 2.0 first
> 2. install nextcord from github over it

this will make it work at an expense of raising a DistributionWarning

**Comment by TAG-Epic** [comment]
That will break a lot of other things. Can you try installing the better aliases branch? (Remember to run aliasgen.py)

**Comment by piotr25691** [comment]
> That will break a lot of other things. Can you try installing the better aliases branch? (Remember to run aliasgen.py)
```py
D:\Aeon-root>python aliasgen.py
  File "D:\Aeon-root\aliasgen.py", line 5
    with open(.aliasignorerc) as f
              ^
SyntaxError: invalid syntax
```

**Comment by piotr25691** [comment]
```py
D:\Aeon-root>python main.py
Traceback (most recent call last):
  File "D:\Aeon-root\main.py", line 10, in <module>
    from dislash import *
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\dislash\__init__.py", line 4, in <module>
    from .interactions import *
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\dislash\interactions\__init__.py", line 1, in <module>
    from .interaction import *
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\dislash\interactions\interaction.py", line 5, in <module>
    from discord.http import Route
ModuleNotFoundError: No module named 'discord.http'
```
dislash completely broke down now because it doesnt know what to use

**Comment by TAG-Epic** [comment]
Don't copy it, download the entire branch from git, run aliasgen then `python3 setup.py install`

**Comment by piotr25691** [comment]
> Don't copy it, download the entire branch from git, run aliasgen then `python3 setup.py install`
```py
D:\Aeon-root>python main.py
Traceback (most recent call last):
  File "D:\Aeon-root\main.py", line 10, in <module>
    from dislash import *
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\dislash\__init__.py", line 5, in <module>
    from .application_commands import *
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\dislash\application_commands\__init__.py", line 2, in <module>
    from .core import *
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\dislash\application_commands\core.py", line 1, in <module>
    from discord.ext.commands.cooldowns import (
ModuleNotFoundError: No module named 'discord.ext.commands.cooldowns'
```
dislash broke in a different way

**Comment by TAG-Epic** [comment]
Could you join our discord and make a help thread?

**Comment by piotr25691** [comment]
> Could you join our discord and make a help thread?

i am in already let me create one

**Comment by ooliver1** [comment]
we got another fix yesterday, could you update from github and try again?

**Comment by piotr25691** [comment]
> we got another fix yesterday, could you update from github and try again?

from the master branch?

**Comment by TAG-Epic** [comment]
Master or pypi, both work. Im gonna close this, feel free to create a help thread if you have further issues.

**Comment by piotr25691** [comment]
i mean not everything is in the aliases because it fails to import `discord.ext.commands.cooldowns`
so idk

**Comment by TAG-Epic** [comment]
Ah seems like there was some issues aliasing subdirs. Fixing now!

**Comment by TAG-Epic** [comment]
Issue fixed properly now. Could you try installing the master branch and trying again?
