### ISSUE TITLE
AttributeError: 'MyView' object has no attribute 'children'

### ISSUE THREAD

**Issue by QuartzWarrior** [nextcord/nextcord#184]
### Summary

When I try to pass message or user to the button, I get this error.

### Reproduction Steps

This is the snippet that I am trying to run.
```py
class MyView(nextcord.ui.View):
    def __init__(self, message, user):
        self.message = message
        self.user = user
    @nextcord.ui.button(label='A button', style=nextcord.ButtonStyle.primary)
    async def button_callback(self, button, interaction):
        button.disabled = True
        self.user.ban()
        interaction.response.send_message('Succesfully banned.', ephemeral=True)


@client.command()
async def buttons(message, user: nextcord.Member=None):
    await message.send(f"What would you like to do with {user}?",view=MyView(message, user))
```

### Minimal Reproducible Code

This is the snippet that I am trying to run.
```python

class MyView(nextcord.ui.View):
    def __init__(self, message, user):
        self.message = message
        self.user = user
    @nextcord.ui.button(label='A button', style=nextcord.ButtonStyle.primary)
    async def button_callback(self, button, interaction):
        button.disabled = True
        self.user.ban()
        interaction.response.send_message('Succesfully banned.', ephemeral=True)


@client.command()
async def buttons(message, user: nextcord.Member=None):
    await message.send(f"What would you like to do with {user}?",view=MyView(message, user))
```

### Expected Results

When I do the command, it should have sent a message with a button called `A button`, and when I click the button, it should ban the passed user.

### Actual Results

It gave me this error:
```
Ignoring exception in on_command_error
Traceback (most recent call last):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/nextcord/ext/commands/core.py", line 168, in wrapped
    ret = await coro(*args, **kwargs)
  File "main.py", line 53, in buttons
    await message.send(f"What would you like to do with {user}?",view=MyView(message))
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/nextcord/abc.py", line 1370, in send
    components = view.to_components()
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/nextcord/ui/view.py", line 197, in to_components
    children = sorted(self.children, key=key)
AttributeError: 'MyView' object has no attribute 'children'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/nextcord/client.py", line 351, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 60, in on_command_error
    raise error
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/nextcord/ext/commands/bot.py", line 995, in invoke
    await ctx.command.invoke(ctx)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/nextcord/ext/commands/core.py", line 895, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/nextcord/ext/commands/core.py", line 177, in wrapped
    raise CommandInvokeError(exc) from exc
nextcord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'MyView' object has no attribute 'children'
```

### Intents

None.

### System Information

```
- Python v3.8.12-final
- nextcord v2.0.0-alpha
    - nextcord pkg_resources: v2.0.0a3
- aiohttp v3.7.4.post0
- system info: Linux 5.11.0-1018-gcp #20~20.04.2-Ubuntu SMP Fri Sep 3 01:01:37 UTC 2021
```

### Checklist

- [X] I have shown the entire traceback, if possible.
- [X] I have searched the open issues for duplicates.
- [X] I have removed my token from display, if visible.

**Comment by TAG-Epic** [comment]
Seems like your issue was [fixed](https://discord.com/channels/881118111967883295/881124672056467456/892680652577706004)

**Comment by QuartzWarrior** [comment]
Oop yea sry
