### ISSUE TITLE
Nextcord doesn't work in python 3.10

### ISSUE THREAD

**Issue by SayHelloRoman** [nextcord/nextcord#204]
### Summary

Nextcord doesn't work in python 3.10

### Reproduction Steps

```python
from nextcord.ext import commands


bot = commands.Bot(command_prefix='!')

@bot.command()
async def ping(ctx):
    await ctx.reply('Pong!')

bot.run('')
```

### Minimal Reproducible Code

```python
bot.run('')
```

### Expected Results

Bot will work

### Actual Results

exception

### Intents

None

### System Information

- Python v3.10.0-final
- nextcord v2.0.0-alpha
    - nextcord pkg_resources: v2.0.0a3
- aiohttp v3.6.2
- system info: Windows 10 10.0.14393

### Checklist

- [x] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

full error:
```
D:\Python\lib\site-packages\aiohttp\connector.py:964: RuntimeWarning: coroutine 'TCPConnector._resolve_host' was never awaited
  hosts = await asyncio.shield(self._resolve_host(
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Traceback (most recent call last):
  File "D:\Проекты\kinglolisss\nextc.py", line 10, in <module>
    bot.run('')
  File "D:\Python\lib\site-packages\nextcord\client.py", line 666, in run
    return future.result()
  File "D:\Python\lib\site-packages\nextcord\client.py", line 645, in runner
    await self.start(*args, **kwargs)
  File "D:\Python\lib\site-packages\nextcord\client.py", line 608, in start
    await self.login(token)
  File "D:\Python\lib\site-packages\nextcord\client.py", line 476, in login
    data = await self.http.static_login(token.strip())
  File "D:\Python\lib\site-packages\nextcord\http.py", line 380, in static_login
    data = await self.request(Route('GET', '/users/@me'))
  File "D:\Python\lib\site-packages\nextcord\http.py", line 273, in request
    async with self.__session.request(method, url, **kwargs) as response:
  File "D:\Python\lib\site-packages\aiohttp\client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "D:\Python\lib\site-packages\aiohttp\client.py", line 480, in _request
    conn = await self._connector.connect(
  File "D:\Python\lib\site-packages\aiohttp\connector.py", line 523, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\Python\lib\site-packages\aiohttp\connector.py", line 858, in _create_connection
    _, proto = await self._create_direct_connection(
  File "D:\Python\lib\site-packages\aiohttp\connector.py", line 964, in _create_direct_connection
    hosts = await asyncio.shield(self._resolve_host(
TypeError: shield() got an unexpected keyword argument 'loop'
```

[python docs](https://docs.python.org/3/library/asyncio-task.html#asyncio.shield): 
```
Deprecated since version 3.8, removed in version 3.10: The loop parameter. This function has been implicitly getting the current running loop since 3.7. See What’s New in 3.10’s Removed section for more information.

Deprecated since version 3.10: Deprecation warning is emitted if aw is not Future-like object and there is no running event loop.
```

**Comment by ooliver1** [comment]
Looks like an issue with aiohttp not nextcord
