### ISSUE TITLE
Scheduled events exception kills process

### ISSUE THREAD

**Issue by Gugu7264** [nextcord/nextcord#345]
### Summary

parse_guild_scheduled_event_user_add kills the process immediately by raising an unhandled exception

### Reproduction Steps

Updated to 2.0.0.a6
Bot instance with no intents specified

- In a guild with a scheduled event
- Run the bot
- Get a member to add themselves to the scheduled events
- Bot breaks

### Minimal Reproducible Code

```python
No code needed, just a Bot instance.
```

### Expected Results

No exception raised, or handled exception.

### Actual Results

Process is terminating.

```py
Sun, 09 Jan 2022 10:16:35] INFO [client.py.run:725] Cleaning up tasks.
[Sun, 09 Jan 2022 10:16:35] INFO [client.py._cancel_tasks:113] Cleaning up after 1 tasks.
[Sun, 09 Jan 2022 10:16:35] INFO [client.py._cancel_tasks:118] All tasks finished cancelling.
[Sun, 09 Jan 2022 10:16:35] INFO [client.py._cleanup_loop:135] Closing the event loop.
Traceback (most recent call last):
  File "50new.py", line 320, in <module>
    bot.run("<leaked token>")
  File "/root/gugumusic/venv/lib/python3.8/site-packages/nextcord/client.py", line 730, in run
    return future.result()
  File "/root/gugumusic/venv/lib/python3.8/site-packages/nextcord/client.py", line 709, in runner
    await self.start(*args, **kwargs)
  File "/root/gugumusic/venv/lib/python3.8/site-packages/nextcord/client.py", line 673, in start
    await self.connect(reconnect=reconnect)
  File "/root/gugumusic/venv/lib/python3.8/site-packages/nextcord/client.py", line 579, in connect
    await self.ws.poll_event()
  File "/root/gugumusic/venv/lib/python3.8/site-packages/nextcord/gateway.py", line 562, in poll_event
    await self.received_message(msg.data)
  File "/root/gugumusic/venv/lib/python3.8/site-packages/nextcord/gateway.py", line 512, in received_message
    func(data)
  File "/root/gugumusic/venv/lib/python3.8/site-packages/nextcord/state.py", line 1761, in parse_guild_scheduled_event_user_add
    event._add_user(u)
  File "/root/gugumusic/venv/lib/python3.8/site-packages/nextcord/scheduled_events.py", line 277, in _add_user
    self._users[user.user.id] = user
AttributeError: 'NoneType' object has no attribute 'id'
```

### Intents

Not specifying, default ig

### System Information

- Python v3.8.12-final
- nextcord v2.0.0-alpha
    - nextcord pkg_resources: v2.0.0a6
- aiohttp v3.8.1
- system info: Linux 4.15.0-122-generic #\124-Ubuntu SMP Thu Oct 15 13:03:05 UTC 2020

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by ooliver1** [comment]
!I have removed my token from display" :lol:

**Comment by Gugu7264** [comment]
> "I have removed my token from display" 😄

I really didn't see it :')
