### ISSUE TITLE
nextcord.Interaction.user gives member_descriptor instead of nextcord.User

### ISSUE THREAD

**Issue by maciclol** [nextcord/nextcord#516]
### Summary

Trying to get the user invoking a slash command, nextcord.Interaction.user returns member_descriptor instead 

### Reproduction Steps

I am trying to get a User object of the user who invoked a specific slash command. When searching for it online, I was told to use `nextcord.Interaction.user`. I tried using it to find the user's ID, but was met with the following error: `AttributeError: 'member_descriptor' object has no attribute 'id'`, which shows that a User object isn't being returned. I have also tried enabling the _server members_ intent, but this didn't help.

### Minimal Reproducible Code

```python
@nextcord.slash_command(description="Gets a user's ID")
async def id(self, interaction: nextcord.Interaction, user: nextcord.Member = nextcord.Interaction.user):
        await interaction.response.send_message(f"ID: {user.id}")
```

### Expected Results

I expected `nextcord.Interaction.user` to return a `User` or a `Member` object, which I would be able to use to find the user's ID.

### Actual Results

```py
Traceback (most recent call last):
  File "C:\Users\uwu\AppData\Roaming\Python\Python39\site-packages\nextcord\client.py", line 415, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\uwu\AppData\Roaming\Python\Python39\site-packages\nextcord\client.py", line 1741, in on_interaction
    await self.process_application_commands(interaction)
  File "C:\Users\uwu\AppData\Roaming\Python\Python39\site-packages\nextcord\client.py", line 1757, in process_application_commands
    await app_cmd.call_from_interaction(interaction)
  File "C:\Users\uwu\AppData\Roaming\Python\Python39\site-packages\nextcord\application_command.py", line 1182, in call_from_interaction
    await self.call(self._state, interaction, interaction.data.get("options", {}))
  File "C:\Users\uwu\AppData\Roaming\Python\Python39\site-packages\nextcord\application_command.py", line 1186, in call
    await super().call(state, interaction, option_data)
  File "C:\Users\uwu\AppData\Roaming\Python\Python39\site-packages\nextcord\application_command.py", line 663, in call
    await self.call_invoke_slash(state, interaction, option_data)
  File "C:\Users\uwu\AppData\Roaming\Python\Python39\site-packages\nextcord\application_command.py", line 704, in call_invoke_slash
    await self.invoke_slash(interaction, **kwargs)
  File "C:\Users\uwu\AppData\Roaming\Python\Python39\site-packages\nextcord\application_command.py", line 719, in invoke_slash
    await self.callback(self._self_argument, interaction, **kwargs)
  File "C:\Users\uwu\Desktop\PUSKARIC_SLASH_RW\cogs\basic.py", line 14, in howgay
    await interaction.response.send_message(f"ID: {user.id}")
AttributeError: 'member_descriptor' object has no attribute 'id'
```

### Intents

130813

### System Information

```
- Python v3.9.7-final
- nextcord v2.0.0-alpha
    - nextcord pkg_resources: v2.0.0a8
- aiohttp v3.8.1
- system info: Windows 10 10.0.19044

```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by DenverCoder1** [comment]
nextcord.Interaction.user is an attribute. That doesn't make any sense in that context. What you want is to get the user from an interaction instance.

Example:

```py
@nextcord.slash_command(description="Gets a user's ID")
async def id(self, interaction: nextcord.Interaction):
        await interaction.response.send_message(f"ID: {interaction.user.id}")
```

**Comment by maciclol** [comment]
Thank you! I somehow didn't realize this was the way I was supposed to do it, it works now!
