### ISSUE TITLE
Setting on_autocomplete on an int SlashOption raises an exception

### ISSUE THREAD

**Issue by Leshaka** [nextcord/nextcord#576]
### Summary

Autocompletetion on a SlashOption of an integer type raises ValueError until any number is provided by the user.

### Reproduction Steps

Make a slash command with an integer parameter.
Add any on_autocomplete function to the parameter.
Try to use the autocomplete function in Discord.

### Minimal Reproducible Code

```python
from nextcord import Interaction
from nextcord.ext import commands

TESTING_GUILD_ID = 1234  # Replace with your testing guild id

bot = commands.Bot(command_prefix="$")


@bot.slash_command(guild_ids=[TESTING_GUILD_ID])
async def yikes(interaction: Interaction, param: int):
    await interaction.response.send_message("yikes")


@yikes.on_autocomplete('param')
async def autocomplete(interaction: Interaction, param):
    return [1, 2, 3]


bot.run('token')
```

### Expected Results

Autocompletion on parameter 'param' returns [1, 2, 3].

### Actual Results

Autocompletion on parameter 'param' raises ValueError until any number is supplied by the user.

```python
Ignoring exception in on_interaction
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/nextcord/client.py", line 417, in _run_event
    await coro(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/nextcord/client.py", line 1806, in on_interaction
    await self.process_application_commands(interaction)
  File "/usr/local/lib/python3.9/site-packages/nextcord/client.py", line 1865, in process_application_commands
    await app_cmd.call_autocomplete_from_interaction(interaction)
  File "/usr/local/lib/python3.9/site-packages/nextcord/application_command.py", line 1828, in call_autocomplete_from_interaction
    await self.call_autocomplete(
  File "/usr/local/lib/python3.9/site-packages/nextcord/application_command.py", line 937, in call_autocomplete
    focused_option_value = await focused_option.handle_slash_argument(
  File "/usr/local/lib/python3.9/site-packages/nextcord/application_command.py", line 472, in handle_slash_argument
    return int(argument)
ValueError: invalid literal for int() with base 10: ''
```

### Intents

nextcord.Intents.default()

### System Information

- Python v3.9.0-final
- nextcord v2.0.0-alpha
    - nextcord pkg_resources: v2.0.0a10
- aiohttp v3.8.1
- system info: Linux 5.10.0-10-amd64 #1 SMP Debian 5.10.84-1 (2021-12-08)

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by ooliver1** [comment]
discord only allows string keys but i agree this might need a better error

**Comment by ooliver1** [comment]
actually, that may not even be the issue here

**Comment by Leshaka** [comment]
The issue happens then call_autocomplete is called on an empty parameter field (not filled by the user yet) and fails to convert it to the corresponding class object. I think it should convert it to None instead in this case. Thanks for the fast answer!

**Comment by ooliver1** [comment]
seems to have been fixed by #530
