### ISSUE TITLE
error with running, cant start the bot

### ISSUE THREAD

**Issue by Ksarqu** [nextcord/nextcord#650]
### Summary

i just tried to run the quickstart from readme

### Reproduction Steps

copied quickstart installed packages with python3 -m pip install nextcord and started it

### Expected Results

make it run

### Actual Results

`Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/nextcord/client.py", line 599, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 494, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.8/dist-packages/nextcord/gateway.py", line 309, in from_client
    socket = await client.http.ws_connect(gateway)
  File "/usr/local/lib/python3.8/dist-packages/nextcord/http.py", line 207, in ws_connect
    return await self.__session.ws_connect(url, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/aiohttp/client.py", line 792, in _ws_connect
    raise WSServerHandshakeError(
aiohttp.client_exceptions.WSServerHandshakeError: 503, message='Invalid response status', url=URL('wss://gateway.discord.gg/?encoding=json&v=9&compress=zlib-stream')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 11, in <module>
    bot.run("here its my token, i edited the log")
  File "/usr/local/lib/python3.8/dist-packages/nextcord/client.py", line 753, in run
    return future.result()
  File "/usr/local/lib/python3.8/dist-packages/nextcord/client.py", line 732, in runner
    await self.start(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/nextcord/client.py", line 696, in start
    await self.connect(reconnect=reconnect)
  File "/usr/local/lib/python3.8/dist-packages/nextcord/client.py", line 648, in connect
    ws_params.update(sequence=self.ws.sequence, resume=True, session=self.ws.session_id)
AttributeError: 'NoneType' object has no attribute 'sequence'`

### Intents

none

### System Information

- Python v3.8.10-final
- nextcord v2.0.0-alpha
    - nextcord pkg_resources: v2.0.0a10
- aiohttp v3.8.1
- system info: Linux 5.4.162-1-pve #1 SMP PVE 5.4.162-2 (Thu, 20 Jan 2022 16:38:53 +0100)

### Checklist

- [x] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by ooliver1** [comment]
this is a discord server error by the looks of things

**Comment by TAG-Epic** [comment]
Shouldnt this be handled cleanly?

**Comment by ooliver1** [comment]
its probably never been done before as the gateway url is obtained via discord http, and usually both services are down at the same time instead of one
