### ISSUE TITLE
Webhook avatar cannot accept bytes type due to TypeError

### ISSUE THREAD

**Issue by Bohaska** [nextcord/nextcord#946]
### Summary

When adding an image in `bytes` type to a webhook using the create_webhook command, I run into a TypeError. 

### Reproduction Steps

I used the `text_channel.create_webhook()` function with an `avatar` attribute with value type `bytes`.

### Minimal Reproducible Code

```python
nextcord import Interaction, SlashOption, Embed, Colour, Webhook
from nextcord.ext import commands
import logging

bot = commands.Bot()


@bot.slash_command(description="Creates a webhook", force_global=True)
async def webhook_test(interaction: Interaction):
    await interaction.response.send_message("Setting up webhook...", ephemeral=True)
    avatar = open("avatar.jpg", "rb")
    webhook = await interaction.channel.create_webhook(name="Test webhook", avatar=avatar, reason="Successfully "
                                                                                                  "created webhook for "
                                                                                                  "testing.")


logging.basicConfig(level=logging.DEBUG, format='%(asctime)s - %(levelname)s - %(message)s')
logging.debug('Start of program')

bot.run("bot_token")

Note: Needs an image named avatar.jpg in the same folder as file.
```

### Expected Results

I expected the command to create a webhook with the avatar included. 

### Actual Results

I got a TypeError: object bytes can't be used in 'await' expression

The full traceback is below:
```
Traceback (most recent call last):
  File "/home/container/.local/lib/python3.11/site-packages/nextcord/application_command.py", line 906, in invoke_callback_with_hooks
    await self(interaction, *args, **kwargs)
  File "/home/container/bot.py", line 32, in webhook_test
    webhook = await interaction.channel.create_webhook(name="Test webhook", avatar=avatar, reason="Successfully created webhook for "
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/container/.local/lib/python3.11/site-packages/nextcord/channel.py", line 620, in create_webhook
    avatar_base64 = await utils.obj_to_base64_data(avatar)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/container/.local/lib/python3.11/site-packages/nextcord/utils.py", line 547, in obj_to_base64_data
    return _bytes_to_base64_data(await obj.read())
                                 ^^^^^^^^^^^^^^^^
TypeError: object bytes can't be used in 'await' expression
The above exception was the direct cause of the following exception:
nextcord.errors.ApplicationInvokeError: Command raised an exception: TypeError: object bytes can't be used in 'await' expression
```

### Intents

None

### System Information

Nextcord version: 2.3.2
(Note: I can't run the version command in my server)

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by DenverCoder1** [comment]
A buffered IO is not currently a valid type that the function accepts.

You can pass bytes, but to do that, you'd call read on it beforehand.

Example:
```py
avatar = open("nextcord-logo.png", "rb").read()
webhook = await channel.create_webhook(name="Testing", avatar=avatar)
await webhook.send("Hello, world!")
```

Another option is to use `nextcord.File`:
```py
avatar = nextcord.File("nextcord-logo.png")
```

I have tested both of these approaches and they are working as expected.
